const fs = require('fs');
let content = fs.readFileSync('src/components/User3DModelStudio.tsx', 'utf8');

const oldModelsStr = `const INITIAL_MODELS: User3DModel[] = [
  {
    id: 'm1',
    title: 'Minifoguete Experimental Alpha-1',
    author: 'Micael Nildo',
    type: 'foguete_completo',
    meshType: 'cylinder_rocket',
    primitiveShape: 'cylinder',
    visible: true,
    locked: false,
    posX: 0,
    posY: 0,
    posZ: 0,
    rotX: 0,
    rotY: 0,
    rotZ: 0,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    color: '#dc2626',
    description: 'Foguetemodelo Classe G com câmara de alumínio e ogiva von Kármán.',
    createdAt: '2026-08-09',
    driveOrVideoLink: 'https://mnanimat.github.io/mnanimat3d'
  },
  {
    id: 'm2',
    title: 'Aletagem Tripla em Fibra de Vidro G10',
    author: 'MNAnimat AeroSpace',
    type: 'aletagem',
    meshType: 'multistage',
    primitiveShape: 'fin',
    visible: true,
    locked: false,
    posX: 2.5,
    posY: 0,
    posZ: 0,
    rotX: 0,
    rotY: 0.5,
    rotZ: 0,
    scaleX: 1.2,
    scaleY: 0.8,
    scaleZ: 1,
    color: '#3b82f6',
    description: 'Conjunto aerodinâmico (3 aletas) projetadas no OpenRocket.',
    createdAt: '2026-08-08'
  }
];`;

const newModelsStr = `const INITIAL_MODELS: User3DModel[] = [
  {
    id: 'nosecone',
    title: 'Ogiva Von Kármán (Nose Cone)',
    author: 'Micael Nildo',
    type: 'peca_solida',
    meshType: 'cylinder_rocket',
    primitiveShape: 'cone',
    visible: true,
    locked: false,
    posX: 0, posY: 4.6, posZ: 0,
    rotX: 0, rotY: 0, rotZ: 0,
    scaleX: 0.8, scaleY: 1.0, scaleZ: 0.8,
    color: '#f8fafc',
    description: 'Carenagem aerodinâmica, abriga a aviônica superior.',
    createdAt: '2026-08-09'
  },
  {
    id: 'avionics',
    title: 'Módulo de Aviônica & Carga Útil',
    author: 'Micael Nildo',
    type: 'eletronica',
    meshType: 'multistage',
    primitiveShape: 'cylinder',
    visible: true,
    locked: false,
    posX: 0, posY: 3.1, posZ: 0,
    rotX: 0, rotY: 0, rotZ: 0,
    scaleX: 0.8, scaleY: 0.5, scaleZ: 0.8,
    color: '#0f172a',
    description: 'Sistema de telemetria, IMU e computadores de voo.',
    createdAt: '2026-08-09'
  },
  {
    id: 'parachute',
    title: 'Paraquedas & Módulo de Recuperação',
    author: 'Micael Nildo',
    type: 'textura_material',
    meshType: 'experimental_mini',
    primitiveShape: 'cylinder',
    visible: true,
    locked: false,
    posX: 0, posY: 2.1, posZ: 0,
    rotX: 0, rotY: 0, rotZ: 0,
    scaleX: 0.8, scaleY: 0.5, scaleZ: 0.8,
    color: '#f59e0b',
    description: 'Paraquedas piloto e principal.',
    createdAt: '2026-08-09'
  },
  {
    id: 'lox',
    title: 'Tanque de Oxidante (LOX)',
    author: 'Micael Nildo',
    type: 'foguete_completo',
    meshType: 'cylinder_rocket',
    primitiveShape: 'cylinder',
    visible: true,
    locked: false,
    posX: 0, posY: 0.6, posZ: 0,
    rotX: 0, rotY: 0, rotZ: 0,
    scaleX: 0.8, scaleY: 1.0, scaleZ: 0.8,
    color: '#e2e8f0',
    description: 'Oxigênio Líquido (LOX).',
    createdAt: '2026-08-09'
  },
  {
    id: 'interstage',
    title: 'Anel Intertanque (Interstage Coupler)',
    author: 'Micael Nildo',
    type: 'peca_solida',
    meshType: 'cylinder_rocket',
    primitiveShape: 'cylinder',
    visible: true,
    locked: false,
    posX: 0, posY: -0.9, posZ: 0,
    rotX: 0, rotY: 0, rotZ: 0,
    scaleX: 0.82, scaleY: 0.5, scaleZ: 0.82,
    color: '#334155',
    description: 'Estrutura de acoplamento entre tanques.',
    createdAt: '2026-08-09'
  },
  {
    id: 'rp1',
    title: 'Tanque de Combustível (RP-1)',
    author: 'Micael Nildo',
    type: 'foguete_completo',
    meshType: 'cylinder_rocket',
    primitiveShape: 'cylinder',
    visible: true,
    locked: false,
    posX: 0, posY: -2.4, posZ: 0,
    rotX: 0, rotY: 0, rotZ: 0,
    scaleX: 0.8, scaleY: 1.0, scaleZ: 0.8,
    color: '#e2e8f0',
    description: 'Querosene Grau Foguete.',
    createdAt: '2026-08-09'
  },
  {
    id: 'nozzle',
    title: 'Câmara de Combustão & Bocal de Exaustão',
    author: 'Micael Nildo',
    type: 'peca_solida',
    meshType: 'cylinder_rocket',
    primitiveShape: 'cone',
    visible: true,
    locked: false,
    posX: 0, posY: -4.3, posZ: 0,
    rotX: 3.1415, rotY: 0, rotZ: 0,
    scaleX: 0.5, scaleY: 0.6, scaleZ: 0.5,
    color: '#475569',
    description: 'Bocal de sino otimizado para nível do mar.',
    createdAt: '2026-08-09'
  },
  {
    id: 'fins',
    title: 'Conjunto de Aletas Aerodinâmicas (4x)',
    author: 'Micael Nildo',
    type: 'aletagem',
    meshType: 'multistage',
    primitiveShape: 'fin',
    visible: true,
    locked: false,
    posX: 0, posY: -3.5, posZ: 0,
    rotX: 0, rotY: 0, rotZ: 0,
    scaleX: 1.5, scaleY: 1.5, scaleZ: 1.5,
    color: '#ef4444',
    description: '4 aletas estabilizadoras em titânio.',
    createdAt: '2026-08-09'
  }
];`;

content = content.replace(oldModelsStr, newModelsStr);
fs.writeFileSync('src/components/User3DModelStudio.tsx', content);
